language: python
python:
    - "3.4"
install: pip install -r requirements.txt
env:
  global:
    - TRAVIS_BUILD=true
script:
    - coverage run --append manage.py test
branches:
  only:
      - master
      - develop
after_success:
    - coveralls
